language: python
python:
  - 3.5
  - nightly
services: postgresql
# command to install dependencies
env:
  - DJANGO=1.10.5
before_install:
  - export DJANGO_SETTINGS_MODULE=your_project.settings
  - export PYTHONPATH=$HOME/builds/your_github_username/your_repo
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - python3 setup.py install
# command to run tests
script: python3 marssite/manage.py test
