# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 21:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('natica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPropid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope')),
            ],
        ),
        migrations.CreateModel(
            name='EmptySlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsdate', models.DateField()),
                ('modified', models.DateTimeField(auto_now=True, help_text='When modified')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('propid', models.CharField(help_text='YYYYs-nnnn (s[emester]:: A|B)', max_length=10, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, help_text='When modified')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obsdate', models.DateField(help_text='Observation date')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When modified')),
                ('frozen', models.BooleanField(default=False, help_text='Protect against changing this slot during a bulk operation.')),
                ('split', models.BooleanField(default=True, help_text='Iff TRUE treat a slot as Split Night (hdr propid must be in schedule lists)')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument')),
                ('proposals', models.ManyToManyField(to='schedule.Proposal')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope')),
            ],
        ),
        migrations.CreateModel(
            name='SlotSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmlfile', models.FileField(upload_to='mars/%Y%m%d/schedule.xml')),
                ('comment', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([('telescope', 'instrument', 'obsdate')]),
        ),
        migrations.AlterIndexTogether(
            name='slot',
            index_together=set([('telescope', 'instrument', 'obsdate')]),
        ),
        migrations.AlterUniqueTogether(
            name='emptyslot',
            unique_together=set([('telescope', 'instrument', 'obsdate')]),
        ),
        migrations.AlterIndexTogether(
            name='emptyslot',
            index_together=set([('telescope', 'instrument', 'obsdate')]),
        ),
    ]
