# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 21:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('regexp', models.CharField(help_text='Regular expression to match against long error string.', max_length=80)),
                ('shortdesc', models.CharField(blank=True, max_length=40)),
                ('example', models.TextField(blank=True, help_text='Example full error message.')),
            ],
        ),
        migrations.CreateModel(
            name='FilenameKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='FloatKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='HdrFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Function name as used in personality.', max_length=40, unique=True)),
                ('documentation', models.TextField(blank=True, help_text='Function description.')),
                ('definition', models.TextField(help_text='Python function BODY')),
                ('inkeywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), default=list, help_text='FITS keywords used by func', size=None)),
                ('outkeywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), default=list, help_text='FITS keywords added or modified by func', size=None)),
            ],
        ),
        migrations.CreateModel(
            name='IngestKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='IngestRecommendedKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RawKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SupportKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
    ]
