# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-22 09:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('natica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('md5sum', models.CharField(db_index=True, help_text='MD5SUM of FITS file', max_length=40, primary_key=True, serialize=False)),
                ('obsday', models.DateField(help_text='Observation Day', null=True)),
                ('srcpath', models.CharField(help_text='Path of file as submitted', max_length=256)),
                ('fstop_host', models.CharField(blank=True, help_text='Host name of more recent fstop', max_length=40)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, help_text='When AuditRecord updated')),
                ('fstop', models.CharField(blank=True, help_text='Most downstream stop of FITS file', max_length=25)),
                ('submitted', models.DateTimeField(blank=True, help_text='When submitted to archive', null=True)),
                ('success', models.NullBooleanField(help_text='Null until ingest attempted.Then True iff Archive reported success on ingest')),
                ('archerr', models.CharField(blank=True, help_text='Archive ingest error message', max_length=256)),
                ('errcode', models.CharField(blank=True, default='', help_text='Error code for error reported from dataq, tada, archive', max_length=10)),
                ('archfile', models.CharField(blank=True, help_text='Basename of FITS file in Archive', max_length=80)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='FITS metadata changed by ingest', null=True)),
                ('staged', models.BooleanField(default=False, help_text='Marked for subsequent action.')),
                ('hide', models.BooleanField(default=False, help_text='Exclude these records in audit reports.')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope')),
            ],
        ),
    ]
