# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 21:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='Prefix for Archive Filename', max_length=10)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='FitsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('md5sum', models.CharField(max_length=32, unique=True)),
                ('filesize', models.BigIntegerField()),
                ('original_filename', models.TextField(max_length=30)),
                ('archive_filename', models.TextField(max_length=30)),
                ('ra', django.contrib.postgres.fields.ranges.FloatRangeField(help_text='RA min,max', null=True)),
                ('dec', django.contrib.postgres.fields.ranges.FloatRangeField(help_text='DEC min,max', null=True)),
                ('exposure', django.contrib.postgres.fields.ranges.FloatRangeField()),
                ('date_obs', django.contrib.postgres.fields.ranges.DateRangeField(help_text='DATE-OBS min,max', null=True)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hdu_idx', models.PositiveSmallIntegerField()),
                ('xtension', models.CharField(blank=True, max_length=40)),
                ('bitpix', models.IntegerField()),
                ('naxis', models.PositiveSmallIntegerField()),
                ('naxisN', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, size=None)),
                ('pcount', models.PositiveIntegerField(null=True)),
                ('gcount', models.PositiveIntegerField(null=True)),
                ('fitsfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.FitsFile')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('name', models.CharField(help_text='Name used in FITS header (field name INSTRUME)', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=1)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProcType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=1)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=1)),
                ('comment', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField()),
                ('prop_id', models.CharField(max_length=10, null=True, unique=True)),
                ('pi', models.CharField(max_length=40)),
                ('proprietary_period', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(help_text='Site (mountain)', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TacInstrumentAlias',
            fields=[
                ('tac', models.CharField(help_text='Name used by TAC Schedule', max_length=20, primary_key=True, serialize=False)),
                ('hdr', models.ForeignKey(help_text='Name used in FITS header', on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('name', models.CharField(help_text='Name used in FITS header (field name TELES', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument'),
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='natica.Proposal'),
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope'),
        ),
        migrations.AddField(
            model_name='fileprefix',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Instrument'),
        ),
        migrations.AddField(
            model_name='fileprefix',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Site'),
        ),
        migrations.AddField(
            model_name='fileprefix',
            name='telescope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='natica.Telescope'),
        ),
    ]
